### ISSUE TITLE
Nuget

### ISSUE THREAD

**Issue by kripergvg** [ymassad/ProceduralDataflow#1]
Do you have nuget package with this library? Because i cant find it

**Comment by ymassad** [comment]
Here it is:
https://www.nuget.org/packages/YMassad.ProceduralDataflow/0.9.1-alpha

If you try to find it from within visual studio, you need to check the box to include pre-released packages.

**Comment by kripergvg** [comment]
Thank you. I think you should add this to readme.

**Comment by ymassad** [comment]
You are right. Thanks. I will update the readme.
